// customers.js
module.exports = [
  {
    phone_number: "+13109082230",
    first_name: "Alice",
    car_year: "2018",
    car_make: "Toyota",
    car_model: "Camry",
    amount_due: "450.00",
    dealer_name: "Cavalier Motors",
    dealer_website: "www.pay.carpay.com",
    regular_amount_due: "0.00",
    pickups_due: "0.00",
    side_notes_due: "0.00",
    recurring_fees_due: "0.00",
    late_fees_due: "0.00",
    other_receivables_due: "0.00",
    live_agent_phone_number: "+1123456789",
    ivr_phone_number: "+18007654321",
    due_date: "2025-07-31",
    rfc_name: "RFC Finance",
    co_buyer_name: "John Doe",
    preferred_language: "es",
    pay_timeframe_cutoff: "10",
    follow_up_days: "2",
    card_on_file: "1234",
  },
  {
    phone_number: "+13109082230",
    first_name: "Bob",
    car_year: "2019",
    car_make: "Honda",
    car_model: "Civic",
    amount_due: "320.00",
    dealer_name: "Sunrise Auto",
    dealer_website: "www.sunriseauto.com",
    regular_amount_due: "0.00",
    pickups_due: "0.00",
    side_notes_due: "0.00",
    recurring_fees_due: "0.00",
    late_fees_due: "0.00",
    other_receivables_due: "0.00",
    live_agent_phone_number: "+15551234567",
    ivr_phone_number: "+18001112222",
    due_date: "2025-08-01",
    rfc_name: "RFC Finance",
    co_buyer_name: "",
    preferred_language: "en",
    pay_timeframe_cutoff: "3",
    follow_up_days: "2",
    card_on_file: "",
  },
  // {
  //   phone_number: "+13109082230",
  //   first_name: "Charlie",
  //   car_year: "2020",
  //   car_make: "Ford",
  //   car_model: "Focus",
  //   amount_due: "280.00",
  //   dealer_name: "Peak Auto",
  //   dealer_website: "www.peakauto.com",
  //   regular_amount_due: "0.00",
  //   pickups_due: "0.00",
  //   side_notes_due: "0.00",
  //   recurring_fees_due: "0.00",
  //   late_fees_due: "0.00",
  //   other_receivables_due: "0.00",
  //   live_agent_phone_number: "+15552345678",
  //   ivr_phone_number: "+18002223333",
  //   due_date: "2025-08-05",
  //   rfc_name: "RFC Finance",
  //   co_buyer_name: "Sarah Lee",
  //   preferred_language: "en",
  //   pay_timeframe_cutoff: "5",
  //   follow_up_days: "3",
  //   card_on_file: "5678",
  // },
  // {
  //   phone_number: "+13109082230",
  //   first_name: "Diana",
  //   car_year: "2017",
  //   car_make: "Chevrolet",
  //   car_model: "Malibu",
  //   amount_due: "400.00",
  //   dealer_name: "Cavalier Motors",
  //   dealer_website: "www.pay.carpay.com",
  //   regular_amount_due: "0.00",
  //   pickups_due: "0.00",
  //   side_notes_due: "0.00",
  //   recurring_fees_due: "0.00",
  //   late_fees_due: "0.00",
  //   other_receivables_due: "0.00",
  //   live_agent_phone_number: "+1123456789",
  //   ivr_phone_number: "+18007654321",
  //   due_date: "2025-07-30",
  //   rfc_name: "RFC Finance",
  //   co_buyer_name: "",
  //   preferred_language: "es",
  //   pay_timeframe_cutoff: "10",
  //   follow_up_days: "2",
  //   card_on_file: "2345",
  // },
  // {
  //   phone_number: "+13109082230",
  //   first_name: "Ethan",
  //   car_year: "2016",
  //   car_make: "Nissan",
  //   car_model: "Altima",
  //   amount_due: "350.00",
  //   dealer_name: "Sunrise Auto",
  //   dealer_website: "www.sunriseauto.com",
  //   regular_amount_due: "0.00",
  //   pickups_due: "0.00",
  //   side_notes_due: "0.00",
  //   recurring_fees_due: "0.00",
  //   late_fees_due: "0.00",
  //   other_receivables_due: "0.00",
  //   live_agent_phone_number: "+15551234567",
  //   ivr_phone_number: "+18001112222",
  //   due_date: "2025-08-10",
  //   rfc_name: "RFC Finance",
  //   co_buyer_name: "Mark Twain",
  //   preferred_language: "en",
  //   pay_timeframe_cutoff: "7",
  //   follow_up_days: "1",
  //   card_on_file: "",
  // },
];
